Update: Option to enter Netlify Url
mathieudutour/medium-to-own-blog pull request #27
Opened 2019-06-02 07:00 UTC by harshattray

- added a prompt to add Netlify Url.

2019-06-02 07:08 UTC, harshattray commented
I've added a prompt where users van enter their Netlify URL,  this is with regards to [issue #12  ](https://github.com/mathieudutour/medium-to-own-blog/issues/12) . Please review and let me know if these are fine 👍

2019-06-02 10:34 UTC, mathieudutour requested changes
That's a good start. I also think we need to create a new commit and push it so that the website gets updated

2019-06-02 10:34 UTC, mathieudutour commented on gatsby-template/gatsby-config.js
> +  siteUrl: '{{ siteURL }}' || 'http://localhost:8000',
The fallback option isn't going to do anything since `{{ siteURL }}` isn't empty. Instead the fallback should be specified in the code.

2019-06-02 10:34 UTC, mathieudutour commented on gatsby-template/gatsby-config.js
> +  // fallback option if NetlifyURL isnt provided
The comment should describe what the field is about

```suggestion
  // the URL where your website is published
  // it is used to show an "Discuss on twitter" link
```

2019-06-02 10:34 UTC, mathieudutour commented on index.js
> +    ]).then(() => withOutputPath(profile))
Don't think that's needed

2019-06-02 10:34 UTC, mathieudutour commented on index.js
> +    return inquirer.prompt([
Not needed as well

2019-06-04 21:20 UTC, Jeevareesha commented
Jeevajee851@gmail.com

2019-06-08 21:36 UTC, mathieudutour commented
merged here: https://github.com/mathieudutour/medium-to-own-blog/commit/1f612695a5f20aeee65634a24345e43ebdda2a3f

2019-06-08 21:36 UTC, closed without merging